practice1/config/routes.rb
Rails.application.routes.draw do
  root "list#index"
  get "list" => "list#index"
  # get 'files/index'
  get "files" => "files#index"
  get 'say/hello'
  get 'say/goodbye'
  get "about" => "say#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

practice1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

practice1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

practice1/app/controllers/files_controller.rb
class FilesController < ApplicationController
  def index
    # path_back = File.join("*")
    if params[:next].present?
      path = File.join(params[:next], "*")
      @files = Dir[path]
    else
      @files = Dir["*"]
    end
  end

  # def path_back
  #   if !params[:next].present?
  # #     path = File.join(params[:next], "*")
  #     @files = Dir[File.join("../")]
  #   end
  # #   end

  # end
end

practice1/app/controllers/list_controller.rb
class ListController < ApplicationController
  def index
  end
end

practice1/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @year = @time.year
  end

  def goodbye
  end
  
  def about
  end
end

practice1/app/helpers/application_helper.rb
module ApplicationHelper
end

practice1/app/helpers/files_helper.rb
module FilesHelper
end

practice1/app/helpers/list_helper.rb
module ListHelper
end

practice1/app/helpers/say_helper.rb
module SayHelper
end

practice1/app/views/files/index.html.erb
<%# <% @files.each do |file| %> 
    <h1><%= link_to "FILE",  @asdasdasd %></h1>
<%# <% end %> 
<%# <p>Find me in app/views/files/index.html.erb</p> %>
<ul>
<% @files.each do |file| %>
    <li class="file"><%= link_to file, files_path(next: file) %></li>
<% end %>
</ul>

practice1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

practice1/app/views/list/index.html.erb
<h1>List#index</h1>
<p>Find me in app/views/list/index.html.erb</p>

practice1/app/views/say/about.html.erb
<h1>About from Rails</h1>
<%= link_to "Hello", say_hello_path %>
<%= link_to "Goodbye", say_goodbye_path %>
<a target="_blank" href="/say/goodbye">Goodbye</a>

practice1/app/views/say/goodbye.html.erb
<h1>Say goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>
<a href="http://localhost:3000/say/hello">Go to hello page</a>

practice1/app/views/say/hello.html.erb
<h1>Hello from Rails</h1>
<p> Time is <%= Time.now %></p>
<p>(c) <%= @year %></p>
<a href="http://localhost:3000/say/goodbye">Go to goodbye page</a>